### PR TITLE
Add contractor file

### PR DESCRIPTION
**Pull request by vjr**
Enable secondary click context menu shortcut entry for elementary OS Files app to automatically open the hasher app with the hash result for selected file and algorithm.

### CODE REVIEW

**Comment by vjr** [comment]
Hello @JeysonFlores  here's another PR and I would like your help in completing the actual deployment of the contractor file to the user home directory `~/.local/share/contractor` in addition to reviewing my novice python code :-) thank you!

**Comment by JeysonFlores** [comment]
Ok, the idea you are giving is really good and makes Hasher fit as part of the OS. The true is that this little app is my first Linux app so I'm not really aware about how this thing works. I'd like to implement it but I would have to learn about contracts and this stuff.

**Comment by JeysonFlores** [comment]
Right now I'm working on multi-threading hashing because right now it really depends on you machine's power to perform fast hashes but if you hash a really heavy file, Hasher freezes until it's hashed, compared or verified(this one is the heaviest). With multi-threading, Hasher could deactivate UI elements while working (as a responsive feature) until the work is done. I would really like to implement this contract stuff alongside multi-threading hashing.

**Comment by JeysonFlores** [comment]
Ok I've been reading the [elementary contractor repository](https://github.com/elementary/contractor) . So basically, the contractor file **needs** to be in the user's home directory (outside the flatpak folder) in order to be detected by the contractor extension right?

**Comment by JeysonFlores** [comment]
According to [this issue](https://github.com/elementary/contractor/issues/34) on the [elementary/contractor ](https://github.com/elementary/contractor) repository:

> There isn't currently a mechanism to getting Contracts as they existed in 5.1 to work at all. 
> I believe the current plan is to work on expanding the XDG desktop file spec to allow Desktop Actions to take file/URI arguments. Then we don't need the contractor service at all, and it will be standards compliant to work on other DEs/distros.

So it seems like contractors don't work for elementary OS 6 Odin.

**Comment by vjr** [comment]
Hi @JeysonFlores   this PR is still draft work in progress... just to let you know that this works in elementary 6 if I manually copy the contract file to the user contractor directory.

So I feel we can keep the PR open in draft state while both you and I can figure out how to configure the flatpak build to copy the file to the user location.

Your comment about the multithread performance to avoid blocking the UI during heavy operation like verify I can open a new PR too.

By the way I have selected the option to allow maintenaners to make edits to my PRs so you can also add any corrections or improvements because I am a novice at python. 

And thanks for working on this nifty little app for app center.

**Pull request closed without merging**
